Data Visuaization BTech Computer Science Stream;
January 2025 Week 3 Lab Exercises-NumPy basics and vectorized computation Exercises
Name: Manas Bijalwan;
Reg Number- 240905402; 
Date: 30/01/2025

In [16]:
# Data Visuaization
# BTech Computer Science Stream, January 2025
# Week 3 Lab Exercises- NumPy basics and vectorized computation Exercises
# Name: Manas Bijalwan, Reg Number- 240905402, Date: 30/01/2025

In [17]:
import numpy as np

In [18]:
# Q1. 

# Generate a 3x4 NumPy array with random integers between 1 and 50. 

arr_a=np.random.randint(1,51,(3,4))
print(arr_a)

[[50 18 47 18]
 [ 1 13  7  2]
 [25 45 42 35]]


In [19]:
# a. Calculate and print the Mean, Median, and Standard Deviation

# Calculating Mean
var_mean=np.mean(arr_a)
print("Mean: ",var_mean)

# Calculating Median
var_median=np.median(arr_a)
print("Median:",var_median)

# Calculating Standard Deviation
var_std_dev=np.std(arr_a)
print("Standrd Deviation: ",var_std_dev)

Mean:  25.25
Median: 21.5
Standrd Deviation:  17.243960295322726


In [20]:
# b. Print the Sum of all elements and the sum of each row.

#Calculating and printing sum
var_sum=np.sum(arr_a)
print("Sum: ",var_sum)

#Calculating and printing sum of rows
var_sum_row=np.sum(arr_a,axis=1)
print("Sum of Rows: ",var_sum_row)

Sum:  303
Sum of Rows:  [133  23 147]


In [21]:
# c. Reshape the 3x4 array into a 2x6 array and print it.

arr_a=arr_a.reshape(2,6)
print(arr_a)

[[50 18 47 18  1 13]
 [ 7  2 25 45 42 35]]


In [22]:
# Q2.

# Create two (3 * 3) matrices using NumPy and print it. Perform
# and print the results of the following linear algebra operations.


arr_c=np.random.randint(1,51,(3,3))
arr_d=np.random.randint(1,51,(3,3))
print("Matrix 1: \n",arr_c)
print("\n\n")
print("Matrix 2: \n\n\n",arr_d)

Matrix 1: 
 [[38 31 40]
 [34 37 31]
 [11 14  2]]



Matrix 2: 


 [[27 29 30]
 [ 6  9 44]
 [37 38 40]]


In [23]:
# a. Matrix addition

arr_sum=np.add(arr_c,arr_d)
print("Sum of Matrix 1 and Matrix 2: \n\n\n",arr_sum)

Sum of Matrix 1 and Matrix 2: 


 [[65 60 70]
 [40 46 75]
 [48 52 42]]


In [24]:
# b. Matrix subtraction

#Matrix 1- Matrix 2
arr_subtract_c_d=np.subtract(arr_c,arr_d)
print("Difference of Matrix 1 and Matrix 2 Matrix 1 - Matrix 2: \n\n\n",arr_subtract_c_d)
print("\n\n")

# Matrix2-Matrix1
arr_subtract_d_c=np.subtract(arr_d,arr_c)
print("Difference of Matrix 2 and Matrix 1 Matrix 2 - Matrix 1: \n\n\n",arr_subtract_d_c)

Difference of Matrix 1 and Matrix 2 Matrix 1 - Matrix 2: 


 [[ 11   2  10]
 [ 28  28 -13]
 [-26 -24 -38]]



Difference of Matrix 2 and Matrix 1 Matrix 2 - Matrix 1: 


 [[-11  -2 -10]
 [-28 -28  13]
 [ 26  24  38]]


In [25]:
# Matrix multiplication (element-wise and dot product)

# Element Wise
# Matrix1 X Matrix2
arr_multiply_c_d=np.multiply(arr_c,arr_d)
print("Multiplication Matrix 1X Matrix 2: \n\n\n",arr_multiply_c_d)
print("\n\n")

# Matrix2 X Matrix1
arr_multiply_d_c=np.multiply(arr_d,arr_c)
print("Multiplication Matrix 2XMatrix 1: \n\n\n",arr_multiply_d_c)
print("\n\n")


# Dot Product(Inner Product of Matrix1.Matrix2)
arr_dot=np.dot(arr_c,arr_d)
print("Dot Product : Matrix 1.Matrix 2: \n\n\n",arr_dot)

Multiplication Matrix 1X Matrix 2: 


 [[1026  899 1200]
 [ 204  333 1364]
 [ 407  532   80]]



Multiplication Matrix 2XMatrix 1: 


 [[1026  899 1200]
 [ 204  333 1364]
 [ 407  532   80]]



Dot Product : Matrix 1.Matrix 2: 


 [[2692 2901 4104]
 [2287 2497 3888]
 [ 455  521 1026]]


In [26]:
# d. Transpose of a matrix

arr_transpose_c=arr_c.transpose()
print("Transpose of Matrix 1: \n\n\n",arr_transpose_c)
print("\n\n")
arr_transpose_d=arr_d.transpose()
print("Transpose of Matrix 2: \n\n\n",arr_transpose_d)

Transpose of Matrix 1: 


 [[38 34 11]
 [31 37 14]
 [40 31  2]]



Transpose of Matrix 2: 


 [[27  6 37]
 [29  9 38]
 [30 44 40]]


In [27]:
# e. Determinant and inverse (if applicable)

# Determinant 
var_det_c=np.linalg.det(arr_c)
print("Determinant of Matrix 1: ",var_det_c)
var_det_d=np.linalg.det(arr_d)
print("Determinant of Matrix 2: ",var_det_d)


# Checking if inverse is possible and printing it
if(var_det_c==0):
    print("Inverse not possible for Matrix 1")
    print("\n\n")
else:
    arr_inverse_c=np.linalg.inv(arr_c)
    print("Inverse of Matrix 1: \n\n\n",arr_inverse_c)
    print("\n\n")
if(var_det_d==0):
    print("Inverse not possible for Matrix 2")
    print("\n\n")
else:
    arr_inverse_d=np.linalg.inv(arr_d)
    print("Inverse of Matrix 2: \n\n\n",arr_inverse_d)
    print("\n\n")

Determinant of Matrix 1:  -2457.0000000000036
Determinant of Matrix 2:  1677.9999999999952
Inverse of Matrix 1: 


 [[ 0.14652015 -0.2026862   0.21123321]
 [-0.11111111  0.14814815 -0.07407407]
 [-0.02808303  0.07773708 -0.14326414]]



Inverse of Matrix 2: 


 [[-0.78188319 -0.01191895  0.59952324]
 [ 0.82717521 -0.01787843 -0.60071514]
 [-0.06257449  0.02800954  0.04112038]]



